apiVersion: v1
kind: Service
metadata:
  name: node-app-service
  namespace: default
  labels:
    app: node-app
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30728
  selector:
    app: node-app
  clusterIP: 10.111.0.28
  clusterIPs:
    - 10.111.0.28
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  allocateLoadBalancerNodePorts: true
  internalTrafficPolicy: Cluster
